BackendBundle\Entity\Category:
    type: entity
    table: categories
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
    lifecycleCallbacks: {  }
