# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        BackendBundle\Entity\User:
            algorithm: bcrypt
            cost: 4
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'
        user_db_provider:
            entity:
                class: BackendBundle:User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        admin:
            pattern:   ^/admin
            anonymous: ~
            provider: in_memory
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
                default_target_path: /admin/panel
                target_path_parameter: redirect_url
                always_use_default_target_path: false


            logout:
                path: /admin/logout
                target: /admin/login

        main:
            anonymous: ~
            provider: user_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: logout
                target: /
            
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    #access_control:
    #    - { path: ^/admin/panel, roles: ROLE_ADMIN }